export const schedules = [
  {
    data: "Azi - 25/04/2024",
    values: [
      {
        id: 0,
        category: "Cycling",
        oraStart: "17:00",
        oraEnd: "18:00",
        trainer: "Andreea",
      },
      {
        id: 1,
        category: "H.I.I.T",
        oraStart: "18:00",
        oraEnd: "19:00",
        trainer: "Alexandra",
      },
      {
        id: 2,
        category: "Fitness",
        oraStart: "19:00",
        oraEnd: "20:00",
        trainer: "Dom",
      },
      {
        id: 3,
        category: "Zumba",
        oraStart: "20:00",
        oraEnd: "21:00",
        trainer: "Melina",
      },
    ],
  },
  {
    data: "Ieri - 24/04/2024",
    values: [
      {
        id: 0,
        category: "Cycling",
        oraStart: "17:00",
        oraEnd: "18:00",
        trainer: "Andreea",
      },
      {
        id: 1,
        category: "H.I.I.T",
        oraStart: "18:00",
        oraEnd: "19:00",
        trainer: "Alexandra",
      },
      {
        id: 2,
        category: "Fitness",
        oraStart: "19:00",
        oraEnd: "20:00",
        trainer: "Dom",
      },
      {
        id: 3,
        category: "Zumba",
        oraStart: "20:00",
        oraEnd: "21:00",
        trainer: "Melina",
      },
      {
        id: 4,
        category: "Fitness",
        oraStart: "21:00",
        oraEnd: "22:00",
        trainer: "Alex",
      },
    ],
  },
  {
    data: "23/04/2024",
    values: [
      {
        id: 0,
        category: "Cycling",
        oraStart: "17:00",
        oraEnd: "18:00",
        trainer: "Andreea",
      },
      {
        id: 1,
        category: "H.I.I.T",
        oraStart: "18:00",
        oraEnd: "19:00",
        trainer: "Alexandra",
      },
      {
        id: 2,
        category: "Fitness",
        oraStart: "19:00",
        oraEnd: "20:00",
        trainer: "Dom",
      },
      {
        id: 3,
        category: "Zumba",
        oraStart: "20:00",
        oraEnd: "21:00",
        trainer: "Melina",
      },
      {
        id: 4,
        category: "Fitness",
        oraStart: "21:00",
        oraEnd: "22:00",
        trainer: "Alex",
      },
    ],
  },
  {
    data: "22/04/2024",
    values: [
      {
        id: 0,
        category: "Cycling",
        oraStart: "17:00",
        oraEnd: "18:00",
        trainer: "Andreea",
      },
      {
        id: 1,
        category: "H.I.I.T",
        oraStart: "18:00",
        oraEnd: "19:00",
        trainer: "Alexandra",
      },
      {
        id: 2,
        category: "Fitness",
        oraStart: "19:00",
        oraEnd: "20:00",
        trainer: "Dom",
      },
      {
        id: 3,
        category: "Zumba",
        oraStart: "20:00",
        oraEnd: "21:00",
        trainer: "Melina",
      },
      {
        id: 4,
        category: "Fitness",
        oraStart: "21:00",
        oraEnd: "22:00",
        trainer: "Alex",
      },
    ],
  },
  {
    data: "21/04/2024",
    values: [
      {
        id: 0,
        category: "Cycling",
        oraStart: "17:00",
        oraEnd: "18:00",
        trainer: "Andreea",
      },
      {
        id: 1,
        category: "H.I.I.T",
        oraStart: "18:00",
        oraEnd: "19:00",
        trainer: "Alexandra",
      },
      {
        id: 2,
        category: "Fitness",
        oraStart: "19:00",
        oraEnd: "20:00",
        trainer: "Dom",
      },
      {
        id: 3,
        category: "Zumba",
        oraStart: "20:00",
        oraEnd: "21:00",
        trainer: "Melina",
      },
      {
        id: 4,
        category: "Fitness",
        oraStart: "21:00",
        oraEnd: "22:00",
        trainer: "Alex",
      },
    ],
  },
];
