import type { Metadata } from "next";

import "./globals.scss";
import Navbar from "@/components/navbar/Navbar";
import ThemeSwitch from "@/app/ThemeSwitch";
import DarkThemeProviders from "./darkThemeProviders";

import AddToCartProvider from "./context/addToCart/AddToCartContext";
import { ContextAPI } from "./context/contextAPI/ContextAPI";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ContextAPI>
          <AddToCartProvider>
            <DarkThemeProviders>
              <ThemeSwitch />

              <main>
                <Navbar />

                {children}
                <Footer />
              </main>
            </DarkThemeProviders>
          </AddToCartProvider>
        </ContextAPI>
      </body>
    </html>
  );
}
